// Code generated by MockGen. DO NOT EDIT.
// Source: greeter.go

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	greetings "github.com/davidklassen/testing-workshop/pkg/greetings"
	gomock "github.com/golang/mock/gomock"
)

// MockGreetingsRepository is a mock of GreetingsRepository interface.
type MockGreetingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGreetingsRepositoryMockRecorder
}

// MockGreetingsRepositoryMockRecorder is the mock recorder for MockGreetingsRepository.
type MockGreetingsRepositoryMockRecorder struct {
	mock *MockGreetingsRepository
}

// NewMockGreetingsRepository creates a new mock instance.
func NewMockGreetingsRepository(ctrl *gomock.Controller) *MockGreetingsRepository {
	mock := &MockGreetingsRepository{ctrl: ctrl}
	mock.recorder = &MockGreetingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGreetingsRepository) EXPECT() *MockGreetingsRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockGreetingsRepository) FindAll() ([]*greetings.Greeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*greetings.Greeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockGreetingsRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockGreetingsRepository)(nil).FindAll))
}

// FindRandom mocks base method.
func (m *MockGreetingsRepository) FindRandom() (*greetings.Greeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRandom")
	ret0, _ := ret[0].(*greetings.Greeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRandom indicates an expected call of FindRandom.
func (mr *MockGreetingsRepositoryMockRecorder) FindRandom() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRandom", reflect.TypeOf((*MockGreetingsRepository)(nil).FindRandom))
}
